#!/usr/bin/env python

# Optional ninja-based script to run all of GREASE's linters
#
# See doc/dev.md.

from argparse import ArgumentParser
from itertools import chain
from os import execvp
from pathlib import Path
from subprocess import run


ninja = """
builddir=.out/

rule hlint
  command = hlint $in && touch $out
  description = hlint

rule ruff-check
  command = ruff check $in && touch $out
  description = ruff check

rule ruff-fmt
  command = ruff format --check $in && touch $out
  description = ruff format

rule spotless
  command = cd ghidra-plugin && ./gradlew spotlessCheck $in && touch $out
  description = spotless

rule todo
  command = python3 scripts/lint/stale-todo.py $in && touch $out
  description = todo

rule typos
  command = typos $in && touch $out
  description = typos

rule ws
  command = python3 scripts/lint/whitespace.py $in && touch $out
  description = whitespace

"""


def build(outs: str, rule: str, ins: str):
    global ninja
    ninja += f"build {outs}: {rule} {ins}\n"


def lint(rule: str, ins: str):
    slug = ins.replace("/", "-") + "." + rule
    build(f"$builddir/{slug}", rule, ins)


def ls_files(pat: str) -> list[str]:
    out = run(["git", "ls-files", pat], capture_output=True, shell=False)
    return out.stdout.strip().decode("utf-8").split("\n")


def hs():
    hs = ls_files("*.hs")
    for path in hs:
        if "elf-edit-core-dump" in path:
            continue
        lint("hlint", path)
        lint("todo", path)


def md():
    md = ls_files("*.md")
    for path in md:
        lint("todo", path)
        lint("typos", path)
        lint("ws", path)


def py():
    py = chain(ls_files("*.py"), ["lint"])
    for path in py:
        lint("ruff-check", path)
        lint("ruff-fmt", path)
        lint("todo", path)


def scala():
    scala = ls_files("*.scala")
    build("$builddir/spotless", "spotless", " ".join(scala))
    for path in scala:
        lint("todo", path)


def go(languages: list[str]):
    if languages is None or "hs" in languages:
        hs()
    if languages is None or "md" in languages:
        md()
    if languages is None or "py" in languages:
        py()
    if languages is None or "scala" in languages:
        scala()
    Path("build.ninja").write_text(ninja)
    execvp("ninja", ["ninja"])


parser = ArgumentParser()
parser.add_argument("-l", "--language", action="append")
# ignore paths passed by ghcid --lint
parser.add_argument("IGNORED", nargs="*")
args = parser.parse_args()
go(args.language)
