#!/usr/bin/env python3
"""
Compare performance between two git commits using multiple profiling methods.

Generated by AI, not extensively reviewed for quality but also not
critical-path.

Collects:
- Cachegrind (deterministic instruction counts)
- RTS statistics (heap allocation, GC metrics)
- Heap census (peak heap, samples via -hT flag)
- Perf counters (instructions, cycles, cache/branch behavior)
- Derived metrics (IPC, cache miss rate, branch miss rate)

Metrics are organized by determinism (deterministic first, noisy last).

Usage:
    ./compare-commits.py <commit1> <commit2> -- [grease-args...]

Example:
    ./compare-commits.py HEAD~1 HEAD -- --symbol test test.x64.elf
"""

import subprocess
import sys
import re
from pathlib import Path
from typing import Dict, Any, Tuple, List
from dataclasses import dataclass


@dataclass
class Stats:
    """Performance statistics from a single run."""

    # RTS stats (deterministic)
    allocated_bytes: int = 0
    copied_bytes: int = 0
    peak_residency: int = 0
    max_slop: int = 0
    total_memory_mb: int = 0
    gen0_collections: int = 0
    gen1_collections: int = 0
    gen0_time: float = 0.0
    gen0_elapsed: float = 0.0
    gen1_time: float = 0.0
    gen1_elapsed: float = 0.0
    total_gc_time: float = 0.0
    total_gc_elapsed: float = 0.0
    mut_time: float = 0.0
    total_time: float = 0.0
    productivity: float = 0.0  # Percentage

    # Cachegrind (deterministic)
    instructions: int = 0
    evacuate_instructions: int = 0
    scavenge_block_instructions: int = 0

    # Perf hardware counters (mostly deterministic)
    perf_instructions: int = 0
    perf_cycles: int = 0
    perf_cache_refs: int = 0
    perf_cache_misses: int = 0
    perf_branches: int = 0
    perf_branch_misses: int = 0

    # Derived metrics (computed from above)
    ipc: float = 0.0  # Instructions per cycle
    cache_miss_rate: float = 0.0  # Percentage
    branch_miss_rate: float = 0.0  # Percentage

    # Perf software events (noisy)
    cpu_clock_ms: float = 0.0
    task_clock_ms: float = 0.0
    context_switches: int = 0
    page_faults: int = 0
    minor_faults: int = 0
    major_faults: int = 0

    # Elapsed time (noisy)
    total_elapsed: float = 0.0
    perf_elapsed: float = 0.0

    # Heap census (deterministic, via -hT flag)
    heap_samples: int = 0
    heap_peak_bytes: int = 0
    heap_peak_time: float = 0.0


def run_command(
    cmd: list[str], cwd: str = None, timeout: int = 300
) -> Tuple[str, str, int]:
    """Run a command and return stdout, stderr, returncode."""
    result = subprocess.run(
        cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout
    )
    return result.stdout, result.stderr, result.returncode


def parse_rts_stats(output: str) -> Dict[str, Any]:
    """Parse GHC RTS statistics."""
    stats = {}

    # Heap allocation
    if m := re.search(r"([\d,]+) bytes allocated in the heap", output):
        stats["allocated_bytes"] = int(m.group(1).replace(",", ""))
    if m := re.search(r"([\d,]+) bytes copied during GC", output):
        stats["copied_bytes"] = int(m.group(1).replace(",", ""))
    if m := re.search(r"([\d,]+) bytes maximum residency", output):
        stats["peak_residency"] = int(m.group(1).replace(",", ""))
    if m := re.search(r"([\d,]+) bytes maximum slop", output):
        stats["max_slop"] = int(m.group(1).replace(",", ""))
    if m := re.search(r"(\d+) MiB total memory in use", output):
        stats["total_memory_mb"] = int(m.group(1))

    # GC collections
    if m := re.search(r"Gen\s+0\s+(\d+) colls", output):
        stats["gen0_collections"] = int(m.group(1))
    if m := re.search(r"Gen\s+1\s+(\d+) colls", output):
        stats["gen1_collections"] = int(m.group(1))

    # GC times
    gen0_match = re.search(
        r"Gen\s+0\s+\d+ colls.*?(\d+\.\d+)s\s+\(\s*(\d+\.\d+)s elapsed\)", output
    )
    if gen0_match:
        stats["gen0_time"] = float(gen0_match.group(1))
        stats["gen0_elapsed"] = float(gen0_match.group(2))

    gen1_match = re.search(
        r"Gen\s+1\s+\d+ colls.*?(\d+\.\d+)s\s+\(\s*(\d+\.\d+)s elapsed\)", output
    )
    if gen1_match:
        stats["gen1_time"] = float(gen1_match.group(1))
        stats["gen1_elapsed"] = float(gen1_match.group(2))

    # Total times
    if m := re.search(r"MUT\s+time\s+(\d+\.\d+)s", output):
        stats["mut_time"] = float(m.group(1))
    if m := re.search(r"GC\s+time\s+(\d+\.\d+)s\s+\(\s*(\d+\.\d+)s elapsed\)", output):
        stats["total_gc_time"] = float(m.group(1))
        stats["total_gc_elapsed"] = float(m.group(2))
    if m := re.search(
        r"Total\s+time\s+(\d+\.\d+)s\s+\(\s*(\d+\.\d+)s elapsed\)", output
    ):
        stats["total_time"] = float(m.group(1))
        stats["total_elapsed"] = float(m.group(2))

    # Productivity - try multiple formats
    # Format: "Productivity  52.1% of total user, 61.7% of total elapsed"
    if m := re.search(
        r"Productivity\s+[\d.]+%[^,]*,\s*([\d.]+)% of total elapsed", output
    ):
        stats["productivity"] = float(m.group(1))
    # Alternative format: just "X.X% elapsed" somewhere
    elif m := re.search(r"([\d.]+)%\s+elapsed", output, re.IGNORECASE):
        stats["productivity"] = float(m.group(1))

    return stats


def parse_cachegrind(output: str) -> Dict[str, Any]:
    """Parse cachegrind annotation output."""
    stats = {}

    # Total instructions
    if m := re.search(r"([\d,]+)\s+\(100\.0%\)\s+PROGRAM TOTALS", output):
        stats["instructions"] = int(m.group(1).replace(",", ""))

    # GC function instructions
    if m := re.search(r"([\d,]+).*?evacuate\s*$", output, re.MULTILINE):
        stats["evacuate_instructions"] = int(m.group(1).replace(",", ""))
    if m := re.search(r"([\d,]+).*?scavenge_block\s*$", output, re.MULTILINE):
        stats["scavenge_block_instructions"] = int(m.group(1).replace(",", ""))

    return stats


def parse_hp_file(hp_path: Path) -> Dict[str, Any]:
    """Parse a .hp heap profile file and extract statistics.

    Returns dict with samples, peak_bytes, peak_time.
    """
    stats = {}
    if not hp_path.exists():
        return stats

    try:
        with open(hp_path) as f:
            lines = [line.strip() for line in f]

        samples = []
        i = 0
        while i < len(lines):
            line = lines[i]

            # Look for BEGIN_SAMPLE
            if line.startswith("BEGIN_SAMPLE"):
                # Extract timestamp
                match = re.match(r"BEGIN_SAMPLE\s+([\d.]+)", line)
                timestamp = float(match.group(1)) if match else 0.0

                sample_total = 0
                i += 1

                # Read data until END_SAMPLE
                while i < len(lines) and not lines[i].startswith("END_SAMPLE"):
                    parts = lines[i].split("\t")
                    if len(parts) >= 2:
                        try:
                            bytes_val = int(parts[1])
                            sample_total += bytes_val
                        except ValueError:
                            pass
                    i += 1

                samples.append((timestamp, sample_total))

            i += 1

        if samples:
            # Find peak heap usage
            peak_bytes = 0
            peak_time = 0.0
            for timestamp, total_bytes in samples:
                if total_bytes > peak_bytes:
                    peak_bytes = total_bytes
                    peak_time = timestamp

            stats["heap_samples"] = len(samples)
            stats["heap_peak_bytes"] = peak_bytes
            stats["heap_peak_time"] = peak_time

    except Exception:
        # Silently ignore errors - heap profiling may not be available
        pass

    return stats


def parse_perf_stat(output: str) -> Dict[str, Any]:
    """Parse perf stat output."""
    stats = {}

    # Hardware counters (if available)
    if m := re.search(r"([\d,]+)\s+instructions", output):
        val = m.group(1)
        if val != "<not supported>":
            stats["perf_instructions"] = int(val.replace(",", ""))
    if m := re.search(r"([\d,]+)\s+cycles", output):
        val = m.group(1)
        if val != "<not supported>":
            stats["perf_cycles"] = int(val.replace(",", ""))
    if m := re.search(r"([\d,]+)\s+cache-references", output):
        val = m.group(1)
        if val != "<not supported>":
            stats["perf_cache_refs"] = int(val.replace(",", ""))
    if m := re.search(r"([\d,]+)\s+cache-misses", output):
        val = m.group(1)
        if val != "<not supported>":
            stats["perf_cache_misses"] = int(val.replace(",", ""))
    if m := re.search(r"([\d,]+)\s+branches", output):
        val = m.group(1)
        if val != "<not supported>":
            stats["perf_branches"] = int(val.replace(",", ""))
    if m := re.search(r"([\d,]+)\s+branch-misses", output):
        val = m.group(1)
        if val != "<not supported>":
            stats["perf_branch_misses"] = int(val.replace(",", ""))

    # Software events
    if m := re.search(r"([\d.]+)\s+msec cpu-clock", output):
        stats["cpu_clock_ms"] = float(m.group(1))
    if m := re.search(r"([\d.]+)\s+msec task-clock", output):
        stats["task_clock_ms"] = float(m.group(1))
    if m := re.search(r"([\d,]+)\s+context-switches", output):
        stats["context_switches"] = int(m.group(1).replace(",", ""))
    if m := re.search(r"([\d,]+)\s+page-faults", output):
        stats["page_faults"] = int(m.group(1).replace(",", ""))
    if m := re.search(r"([\d,]+)\s+minor-faults", output):
        stats["minor_faults"] = int(m.group(1).replace(",", ""))
    if m := re.search(r"([\d,]+)\s+major-faults", output):
        stats["major_faults"] = int(m.group(1).replace(",", ""))
    if m := re.search(r"([\d.]+) seconds time elapsed", output):
        stats["perf_elapsed"] = float(m.group(1))

    return stats


def collect_stats(binary: str, cli_args: List[str]) -> Stats:
    """Collect all performance statistics for a binary."""
    stats = Stats()

    # 1. RTS stats
    print("  Running with RTS stats...")
    cmd = [binary] + cli_args + ["+RTS", "-s"]
    stdout, stderr, _ = run_command(cmd)
    rts_data = parse_rts_stats(stderr)
    for key, val in rts_data.items():
        setattr(stats, key, val)

    # 2. Cachegrind
    print("  Running cachegrind...")
    cachegrind_file = "/tmp/cachegrind.out"
    cmd = [
        "valgrind",
        "--tool=cachegrind",
        f"--cachegrind-out-file={cachegrind_file}",
        binary,
    ] + cli_args
    stdout, stderr, _ = run_command(cmd, timeout=600)
    stdout, stderr, _ = run_command(["cg_annotate", cachegrind_file])
    cg_data = parse_cachegrind(stdout)
    for key, val in cg_data.items():
        setattr(stats, key, val)

    # 3. Perf stats
    print("  Running perf stat...")
    events = [
        "instructions",
        "cycles",
        "cache-references",
        "cache-misses",
        "branches",
        "branch-misses",
        "cpu-clock",
        "task-clock",
        "context-switches",
        "page-faults",
        "minor-faults",
        "major-faults",
    ]
    cmd = ["perf", "stat", "-e", ",".join(events), binary] + cli_args
    stdout, stderr, _ = run_command(cmd)
    perf_data = parse_perf_stat(stderr)
    for key, val in perf_data.items():
        setattr(stats, key, val)

    # 4. Heap census (via -hT flag)
    # Running with -hT (heap by closure type) to get .hp file
    print("  Running heap census...")
    try:
        # Extract binary base name for .hp file
        binary_name = Path(binary).stem
        hp_file = Path(f"{binary_name}.hp")

        # Clean up any existing .hp file
        hp_file.unlink(missing_ok=True)

        # Run with -hT flag and -i0.01 for 10ms sampling interval (100 samples/sec)
        cmd = [binary] + cli_args + ["+RTS", "-hT", "-i0.01", "-RTS"]
        stdout, stderr, returncode = run_command(cmd)

        if returncode == 0 and hp_file.exists():
            hp_data = parse_hp_file(hp_file)
            for key, val in hp_data.items():
                setattr(stats, key, val)
            # Clean up
            hp_file.unlink(missing_ok=True)
            print("  ✓ Heap census data collected")
        else:
            print("  ⚠ Heap census unavailable (unexpected)")
    except Exception as e:
        # Continue if heap census fails
        print(f"  ⚠ Heap census failed: {e}")

    # 5. Compute derived metrics
    if stats.perf_instructions > 0 and stats.perf_cycles > 0:
        stats.ipc = stats.perf_instructions / stats.perf_cycles

    if stats.perf_cache_refs > 0:
        stats.cache_miss_rate = (stats.perf_cache_misses / stats.perf_cache_refs) * 100

    if stats.perf_branches > 0:
        stats.branch_miss_rate = (stats.perf_branch_misses / stats.perf_branches) * 100

    return stats


def format_number(num: int | float) -> str:
    """Format number with commas."""
    if isinstance(num, float):
        return f"{num:,.2f}"
    return f"{num:,}"


def calculate_improvement(
    old_val: int | float, new_val: int | float, higher_is_better: bool = False
) -> str:
    """Calculate percentage improvement.

    Args:
        old_val: Old value
        new_val: New value
        higher_is_better: If True, positive change is good (e.g., IPC).
                         If False, negative change is good (e.g., time, memory).
    """
    if old_val == 0:
        return "-"
    diff_pct = 100 * (new_val - old_val) / old_val
    if abs(diff_pct) < 0.01:
        return "~same"
    sign = "+" if diff_pct > 0 else ""

    # Determine if this is an improvement
    is_improvement = (diff_pct > 1.0 and higher_is_better) or (
        diff_pct < -1.0 and not higher_is_better
    )

    # Bold if significant improvement (>1%)
    if is_improvement:
        return f"**{sign}{diff_pct:.2f}%**"
    return f"{sign}{diff_pct:.2f}%"


def generate_table(
    commit1: str, stats1: Stats, commit2: str, stats2: Stats, cli_args: List[str]
) -> str:
    """Generate Markdown comparison table."""

    lines = [
        f"## Performance Comparison: {commit1[:8]} vs {commit2[:8]}",
        "",
        f"Command: `grease {' '.join(cli_args)}`",
        "",
        "| Metric | " + commit1[:8] + " | " + commit2[:8] + " | Change |",
        "|--------|"
        + "-" * len(commit1[:8])
        + "|"
        + "-" * len(commit2[:8])
        + "|--------|",
    ]

    # Deterministic metrics first
    lines.extend(
        [
            "| **Cachegrind (Deterministic)** | | | |",
            f"| Total instructions | {format_number(stats1.instructions)} | {format_number(stats2.instructions)} | {calculate_improvement(stats1.instructions, stats2.instructions)} |",
        ]
    )

    if stats1.evacuate_instructions > 0:
        lines.append(
            f"| evacuate (GC) | {format_number(stats1.evacuate_instructions)} | {format_number(stats2.evacuate_instructions)} | {calculate_improvement(stats1.evacuate_instructions, stats2.evacuate_instructions)} |"
        )
    if stats1.scavenge_block_instructions > 0:
        lines.append(
            f"| scavenge_block (GC) | {format_number(stats1.scavenge_block_instructions)} | {format_number(stats2.scavenge_block_instructions)} | {calculate_improvement(stats1.scavenge_block_instructions, stats2.scavenge_block_instructions)} |"
        )

    lines.extend(
        [
            "| **RTS Heap (Deterministic)** | | | |",
            f"| Allocated bytes | {format_number(stats1.allocated_bytes)} | {format_number(stats2.allocated_bytes)} | {calculate_improvement(stats1.allocated_bytes, stats2.allocated_bytes)} |",
            f"| Copied during GC | {format_number(stats1.copied_bytes)} | {format_number(stats2.copied_bytes)} | {calculate_improvement(stats1.copied_bytes, stats2.copied_bytes)} |",
            f"| Peak residency | {format_number(stats1.peak_residency)} | {format_number(stats2.peak_residency)} | {calculate_improvement(stats1.peak_residency, stats2.peak_residency)} |",
            f"| Maximum slop | {format_number(stats1.max_slop)} | {format_number(stats2.max_slop)} | {calculate_improvement(stats1.max_slop, stats2.max_slop)} |",
            f"| Total memory | {stats1.total_memory_mb} MiB | {stats2.total_memory_mb} MiB | {calculate_improvement(stats1.total_memory_mb, stats2.total_memory_mb)} |",
            "| **RTS GC (Deterministic)** | | | |",
            f"| Gen 0 collections | {stats1.gen0_collections} | {stats2.gen0_collections} | {calculate_improvement(stats1.gen0_collections, stats2.gen0_collections)} |",
            f"| Gen 1 collections | {stats1.gen1_collections} | {stats2.gen1_collections} | {calculate_improvement(stats1.gen1_collections, stats2.gen1_collections)} |",
            f"| Gen 0 time | {stats1.gen0_time:.3f}s | {stats2.gen0_time:.3f}s | {calculate_improvement(stats1.gen0_time, stats2.gen0_time)} |",
            f"| Gen 1 time | {stats1.gen1_time:.3f}s | {stats2.gen1_time:.3f}s | {calculate_improvement(stats1.gen1_time, stats2.gen1_time)} |",
            f"| Total GC time | {stats1.total_gc_time:.3f}s | {stats2.total_gc_time:.3f}s | {calculate_improvement(stats1.total_gc_time, stats2.total_gc_time)} |",
            f"| MUT time | {stats1.mut_time:.3f}s | {stats2.mut_time:.3f}s | {calculate_improvement(stats1.mut_time, stats2.mut_time)} |",
            f"| Total CPU time | {stats1.total_time:.3f}s | {stats2.total_time:.3f}s | {calculate_improvement(stats1.total_time, stats2.total_time)} |",
        ]
    )

    # Productivity (if available)
    if stats1.productivity > 0:
        lines.append(
            f"| Productivity | {stats1.productivity:.1f}% | {stats2.productivity:.1f}% | {calculate_improvement(stats1.productivity, stats2.productivity, higher_is_better=True)} |"
        )

    # Heap census (if available)
    if stats1.heap_samples > 0:
        lines.extend(
            [
                "| **Heap Census (Deterministic)** | | | |",
                f"| Heap samples | {stats1.heap_samples} | {stats2.heap_samples} | {calculate_improvement(stats1.heap_samples, stats2.heap_samples)} |",
                f"| Peak heap | {format_number(stats1.heap_peak_bytes)} bytes | {format_number(stats2.heap_peak_bytes)} bytes | {calculate_improvement(stats1.heap_peak_bytes, stats2.heap_peak_bytes)} |",
                f"| Peak at | {stats1.heap_peak_time:.2f}s | {stats2.heap_peak_time:.2f}s | {calculate_improvement(stats1.heap_peak_time, stats2.heap_peak_time)} |",
            ]
        )

    # Perf hardware counters (if available)
    if stats1.perf_instructions > 0:
        lines.extend(
            [
                "| **Perf Hardware (Mostly Deterministic)** | | | |",
                f"| Instructions | {format_number(stats1.perf_instructions)} | {format_number(stats2.perf_instructions)} | {calculate_improvement(stats1.perf_instructions, stats2.perf_instructions)} |",
            ]
        )
        if stats1.perf_cycles > 0:
            lines.append(
                f"| Cycles | {format_number(stats1.perf_cycles)} | {format_number(stats2.perf_cycles)} | {calculate_improvement(stats1.perf_cycles, stats2.perf_cycles)} |"
            )
        if stats1.perf_cache_refs > 0:
            lines.append(
                f"| Cache references | {format_number(stats1.perf_cache_refs)} | {format_number(stats2.perf_cache_refs)} | {calculate_improvement(stats1.perf_cache_refs, stats2.perf_cache_refs)} |"
            )
        if stats1.perf_cache_misses > 0:
            lines.append(
                f"| Cache misses | {format_number(stats1.perf_cache_misses)} | {format_number(stats2.perf_cache_misses)} | {calculate_improvement(stats1.perf_cache_misses, stats2.perf_cache_misses)} |"
            )
        if stats1.perf_branches > 0:
            lines.append(
                f"| Branches | {format_number(stats1.perf_branches)} | {format_number(stats2.perf_branches)} | {calculate_improvement(stats1.perf_branches, stats2.perf_branches)} |"
            )
        if stats1.perf_branch_misses > 0:
            lines.append(
                f"| Branch misses | {format_number(stats1.perf_branch_misses)} | {format_number(stats2.perf_branch_misses)} | {calculate_improvement(stats1.perf_branch_misses, stats2.perf_branch_misses)} |"
            )
        # Derived metrics
        if stats1.ipc > 0:
            lines.append(
                f"| IPC (Instructions/Cycle) | {stats1.ipc:.3f} | {stats2.ipc:.3f} | {calculate_improvement(stats1.ipc, stats2.ipc, higher_is_better=True)} |"
            )
        if stats1.cache_miss_rate > 0:
            lines.append(
                f"| Cache miss rate | {stats1.cache_miss_rate:.2f}% | {stats2.cache_miss_rate:.2f}% | {calculate_improvement(stats1.cache_miss_rate, stats2.cache_miss_rate)} |"
            )
        if stats1.branch_miss_rate > 0:
            lines.append(
                f"| Branch miss rate | {stats1.branch_miss_rate:.2f}% | {stats2.branch_miss_rate:.2f}% | {calculate_improvement(stats1.branch_miss_rate, stats2.branch_miss_rate)} |"
            )

    # Noisy metrics last
    lines.extend(
        [
            "| **Perf Software (Noisy)** | | | |",
            f"| CPU clock | {stats1.cpu_clock_ms:.2f} ms | {stats2.cpu_clock_ms:.2f} ms | {calculate_improvement(stats1.cpu_clock_ms, stats2.cpu_clock_ms)} |",
            f"| Task clock | {stats1.task_clock_ms:.2f} ms | {stats2.task_clock_ms:.2f} ms | {calculate_improvement(stats1.task_clock_ms, stats2.task_clock_ms)} |",
            f"| Context switches | {stats1.context_switches} | {stats2.context_switches} | {calculate_improvement(stats1.context_switches, stats2.context_switches)} |",
            f"| Page faults | {format_number(stats1.page_faults)} | {format_number(stats2.page_faults)} | {calculate_improvement(stats1.page_faults, stats2.page_faults)} |",
            f"| Minor faults | {format_number(stats1.minor_faults)} | {format_number(stats2.minor_faults)} | {calculate_improvement(stats1.minor_faults, stats2.minor_faults)} |",
            f"| Major faults | {format_number(stats1.major_faults)} | {format_number(stats2.major_faults)} | {calculate_improvement(stats1.major_faults, stats2.major_faults)} |",
            "| **Elapsed Time (Noisy)** | | | |",
            f"| RTS elapsed | {stats1.total_elapsed:.3f}s | {stats2.total_elapsed:.3f}s | {calculate_improvement(stats1.total_elapsed, stats2.total_elapsed)} |",
            f"| Gen 0 elapsed | {stats1.gen0_elapsed:.3f}s | {stats2.gen0_elapsed:.3f}s | {calculate_improvement(stats1.gen0_elapsed, stats2.gen0_elapsed)} |",
            f"| Gen 1 elapsed | {stats1.gen1_elapsed:.3f}s | {stats2.gen1_elapsed:.3f}s | {calculate_improvement(stats1.gen1_elapsed, stats2.gen1_elapsed)} |",
            f"| Total GC elapsed | {stats1.total_gc_elapsed:.3f}s | {stats2.total_gc_elapsed:.3f}s | {calculate_improvement(stats1.total_gc_elapsed, stats2.total_gc_elapsed)} |",
            f"| Perf elapsed | {stats1.perf_elapsed:.3f}s | {stats2.perf_elapsed:.3f}s | {calculate_improvement(stats1.perf_elapsed, stats2.perf_elapsed)} |",
        ]
    )

    # Add summary of key improvements
    lines.append("")
    lines.append("### Key Changes")
    lines.append("")

    improvements = []
    regressions = []

    # Check deterministic metrics for significant changes
    if abs(stats2.instructions - stats1.instructions) / stats1.instructions > 0.01:
        pct = ((stats2.instructions - stats1.instructions) / stats1.instructions) * 100
        if pct < 0:
            improvements.append(f"Instructions: {pct:.2f}%")
        else:
            regressions.append(f"Instructions: +{pct:.2f}%")

    if (
        abs(stats2.allocated_bytes - stats1.allocated_bytes) / stats1.allocated_bytes
        > 0.01
    ):
        pct = (
            (stats2.allocated_bytes - stats1.allocated_bytes) / stats1.allocated_bytes
        ) * 100
        if pct < 0:
            improvements.append(f"Heap allocation: {pct:.2f}%")
        else:
            regressions.append(f"Heap allocation: +{pct:.2f}%")

    if abs(stats2.gen0_collections - stats1.gen0_collections) > 0:
        diff = stats2.gen0_collections - stats1.gen0_collections
        if diff < 0:
            improvements.append(f"Gen 0 collections: {diff}")
        else:
            regressions.append(f"Gen 0 collections: +{diff}")

    if (
        stats1.total_elapsed > 0
        and abs(stats2.total_elapsed - stats1.total_elapsed) / stats1.total_elapsed
        > 0.01
    ):
        pct = (
            (stats2.total_elapsed - stats1.total_elapsed) / stats1.total_elapsed
        ) * 100
        if pct < 0:
            improvements.append(f"Elapsed time: {pct:.2f}%")
        else:
            regressions.append(f"Elapsed time: +{pct:.2f}%")

    if improvements:
        lines.append("**Improvements:**")
        for imp in improvements:
            lines.append(f"- {imp}")
        if regressions:
            lines.append("")

    if regressions:
        lines.append("**Regressions:**")
        for reg in regressions:
            lines.append(f"- {reg}")

    if not improvements and not regressions:
        lines.append("No significant changes detected (< 1% difference)")

    return "\n".join(lines)


def main():
    # Parse arguments
    if "--" not in sys.argv:
        print("Usage: ./compare-commits.py <commit1> <commit2> -- [grease-args...]")
        print("Example: ./compare-commits.py HEAD~1 HEAD -- --symbol test test.x64.elf")
        sys.exit(1)

    separator_idx = sys.argv.index("--")
    if separator_idx < 3:
        print("Usage: ./compare-commits.py <commit1> <commit2> -- [grease-args...]")
        print("Example: ./compare-commits.py HEAD~1 HEAD -- --symbol test test.x64.elf")
        sys.exit(1)

    commit1 = sys.argv[1]
    commit2 = sys.argv[2]
    cli_args = sys.argv[separator_idx + 1 :]

    if not cli_args:
        print("Error: No grease arguments provided after '--'")
        sys.exit(1)

    binary_path = "dist-newstyle/build/aarch64-linux/ghc-9.10.2/grease-exe-0.1.0.0/x/grease/build/grease/grease"

    print(f"Comparing: {commit1} vs {commit2}")
    print(f"Command: grease {' '.join(cli_args)}")

    # Save current state
    print("\nSaving current git state...")
    current_branch, _, _ = run_command(["git", "rev-parse", "--abbrev-ref", "HEAD"])
    current_branch = current_branch.strip()

    try:
        # Collect stats for commit1
        print(f"\n=== Building and testing {commit1} ===")
        run_command(["git", "checkout", commit1])
        print("Cleaning build artifacts...")
        run_command(["cabal", "clean"])
        print("Building (with -rtsopts for heap census)...")
        run_command(
            ["cabal", "build", "grease-exe:exe:grease", "--ghc-options=-rtsopts"],
            timeout=1800,
        )
        print("Collecting stats...")
        stats1 = collect_stats(binary_path, cli_args)

        # Collect stats for commit2
        print(f"\n=== Building and testing {commit2} ===")
        run_command(["git", "checkout", commit2])
        print("Cleaning build artifacts...")
        run_command(["cabal", "clean"])
        print("Building (with -rtsopts for heap census)...")
        run_command(
            ["cabal", "build", "grease-exe:exe:grease", "--ghc-options=-rtsopts"],
            timeout=1800,
        )
        print("Collecting stats...")
        stats2 = collect_stats(binary_path, cli_args)

        # Generate table
        print("\n" + "=" * 80)
        table = generate_table(commit1, stats1, commit2, stats2, cli_args)
        print(table)
        print("=" * 80)

        # Save to file
        output_file = Path("comparison.md")
        output_file.write_text(table)
        print(f"\nTable saved to {output_file}")

    except KeyboardInterrupt:
        print("\n\nInterrupted by user!")
        raise
    except Exception as e:
        print(f"\n\nError occurred: {e}")
        import traceback

        traceback.print_exc()
        raise
    finally:
        # Always restore git state
        print(f"\nRestoring git state to {current_branch}...")
        run_command(["git", "checkout", current_branch])


if __name__ == "__main__":
    main()
