name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["9.4.8", "9.6.6", "9.8.4"]
        os: [ubuntu-22.04]
      # complete all jobs
      fail-fast: false
    name: GREASE - GHC v${{ matrix.ghc }}
    steps:
    - run: cabal --version

    - uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
